org: dickey
app: aws-rest-api
service: aws-rest-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::aws-rest-api-dev-serverlessdeploymentbucket-rugqfz80lw8r/*'

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'